version: "3.8"
services:
  {{cookiecutter.project_slug}}:
    build: .
    container_name: {{cookiecutter.project_slug}}_container
    volumes:
      - .:/app
    ports:
      - "8888:8888"
    command: ["/bin/bash", "-c", "poetry run python -m http.server 8888"]
